default: faketelnetd

faketelnetd: main.o TelnetServerSocket.o settings.o settingvalue.o logger.o libsocket++/libsocket++.a
	g++  *.o -o faketelnetd -Llibsocket++/ -lsocket++ -lpthread

libsocket++/libsocket++.a:
	make -C libsocket++/

main.o: main.cpp
	g++ -c main.cpp
	
TelnetServerSocket.o: TelnetServerSocket.cpp
	g++ -c TelnetServerSocket.cpp
	
logger.o: logger.cpp
	g++ -c logger.cpp
	
settings.o: settings.cpp
	g++ -c settings.cpp
	
settingvalue.o: settingvalue.cpp
	g++ -c settingvalue.cpp
